New upstream release
* New upstream release
* Fix "AttributeError: 'tuple' object has no attribute 'rfind'"
  by upgrading to a newer version of mercurial-git (Closes: #785367)